variables:
  DOCKER_ADDRESS: gitlab.bangwol08.com:5050
  IMAGE_NAME: gitlab.bangwol08.com:5050/bangwol08/healthcare_backend/user:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy

get_files:  # Dockerfile 및 설정 파일 가져오기
  image: bitnami/git:latest
  stage: build
  before_script:
    - git config --global user.name "gitlab runner"
    - git config --global user.email "bangwol08@gmail.com"
  script:
    - git clone -b main --single-branch https://$GITLAB_ID:$GITLAB_TOKEN@gitlab.bangwol08.com/bangwol08/healthcare_backend.git
  artifacts:
    paths:
      - healthcare_backend
  rules:
  - if: $CI_COMMIT_BRANCH == "user"  
    when: always
    allow_failure: false
  
image_build:  # Dockerfile push
  image: docker:latest
  stage: build
  needs: [get_files]
  dependencies:
    - get_files
  before_script:
    - ls user
    - ls 
    - cd healthcare_backend
    - ls
    - pwd
    - cp config.py ../
    - cp Dockerfile ../
    - cp requirements.txt ../
    - cp database.py ../
    - cp models.py ../
    - cd ../
    - ls
  script:
    - docker login -u $TOKEN_USER -p $TOKEN_PASSWORD $DOCKER_ADDRESS
    - docker build -t $IMAGE_NAME --no-cache .
    - docker push $IMAGE_NAME
  artifacts:
    paths:
      - healthcare_backend
  rules:
  - if: $CI_COMMIT_BRANCH == "user"  
    when: always
    allow_failure: false

get_kustomization:
  image: bitnami/git:latest
  stage: build
  needs: [image_build]
  before_script:
    - git config --global user.name "gitlab runner"
    - git config --global user.email "bangwol08@gmail.com"
  script:
    - git clone -b main --single-branch https://$GITLAB_ID:$GITLAB_TOKEN@gitlab.bangwol08.com/bangwol08/healthcare_deploy.git
  artifacts:
    paths:
      - healthcare_deploy
  rules:
  - if: $CI_COMMIT_BRANCH == "user"  
    when: always
    allow_failure: false

set_kustomization:
  image: gitlab.bangwol08.com:5050/bangwol08/healthcare_front/kustomize:latest
  stage: deploy
  needs: [get_kustomization]
  before_script:
    - cd healthcare_deploy
  script:
    - kustomize edit set image user-image=$IMAGE_NAME
    - cat kustomization.yaml
  artifacts:
    paths:
      - healthcare_deploy
  rules:
  - if: $CI_COMMIT_BRANCH == "user"  
    when: always
    allow_failure: false

push_kustomization:
  image: bitnami/git:latest
  stage: deploy
  needs: [set_kustomization]
  before_script:
    - cd healthcare_deploy
    - cat kustomization.yaml
    - git config --global user.name "gitlab runner"
    - git config --global user.email "bangwol08@gmail.com"
    - git branch -M user-staging
  script:
    - git status
    - git add kustomization.yaml
    - git commit -m "change $BRANCHNAME ver $CI_COMMIT_SHORT_SHA"

    - git push origin user-staging

  rules:
  - if: $CI_COMMIT_BRANCH == "user"  
    when: always
    allow_failure: false
  




    